### PR TITLE
Pal 895 fix integration test

### PR DESCRIPTION
**Pull request by kg981167224**
Draft to get PR build

### CODE REVIEW

**Review by dev930018 — APPROVED** [review]
Can we keep the comment in the redis yaml to re-enable the redis health endpoint with redis after we have spring-boot 2.4.x?

**Review by dev930018 — CHANGES_REQUESTED** [review]
Does this change need to be applied to any other services with redis enabled? I'd expect this to be needed for policy, resource, attribute-masking and filtered-resource, but the test is passing so...

**Comment by kg981167224** [comment]
> Can we keep the comment in the redis yaml to re-enable the redis health endpoint with redis after we have spring-boot 2.4.x?

Done

**Comment by kg981167224** [comment]
> Does this change need to be applied to any other services with redis enabled? I'd expect this to be needed for policy, resource, attribute-masking and filtered-resource, but the test is passing so...

filtered-resource-service already had health disabled in the application.yaml.
Other services i.e. policy and resource have RedisAutoConfiguration disabled in 1 or more profiles i.e. application.yaml.

`  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
     - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
`

**Review by dev930018 — DISMISSED** [review]

**Comment by dev930018** [comment]
Assert that pr-merge here https://github.com/gchq/Palisade-integration-tests/pull/84 passes

**Comment by kg981167224** [comment]
When merged branch https://github.com/gchq/Palisade-integration-tests/tree/PAL-895-Fix-integration-test can be deleted. It was created just to run the tests.

**Review by dev-958 — APPROVED** [review]

**Review by developer01189998819991197253 — APPROVED** [review]

**Review by pd104923 — APPROVED** [review]

**Review by ac74475 — APPROVED** [review]

**Pull request merged**
